### ISSUE TITLE
Shopify Chrome Extension v1

### ISSUE THREAD

**Issue by julionc** [julionc/shopify-chrome-extension#1]
## Chrome Extension

I'll be honest, I am trying to launch [my first Shopify store](https://www.shopify.com/?ref=vitalogy), but I have some issue to update description and know about inventory quantity quickly. So I'm working on an extension to help me with that.
### TODO
- [x] Basic Chrome Extension Skeleton
- [x] Detect and get data for the Product 
- [x] Detect and clean-up the Product URL with query strings.
- [ ] Add custom images & Icons
- [ ] A simple marketing site `gh-page`
- [ ] MetaFields Editor support
- [ ] Find a better name & branding
- [ ] Publish in the Chrome Web Store

**Heads up!** Please use issues for questions, comments, and feedback about particular changes.
We'll cross reference them here as they come up.
